[book]
authors = ["peter"]
language = "en"
multilingual = false
src = "src"
title = "Maple ESP32 Series Development Board User Manual"

[build]
build-dir = "../docs_en/maple_esp32/"


[output.html]
sidebar = true  # 关键配置：强制显示侧边栏（禁用自动隐藏）
