[book]
authors = ["peter"]
language = "zh"
multilingual = false
src = "src"
title = "CH32H417系列开发板使用手册"

[build]
build-dir = "../docs/ch32h417/"


[output.html]
sidebar = true  # 关键配置：强制显示侧边栏（禁用自动隐藏）

